# Generated by Django 4.1.13 on 2024-08-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('image_url', models.URLField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('abilities', models.TextField()),
                ('type_1', models.CharField(max_length=50)),
                ('type_2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
